### ISSUE TITLE
Not an issue: I wanted to understand the below snippet. can you help me please 

### ISSUE THREAD

**Issue by jamesjohnson1025** [nbroad1881/pii-data-detection#1]
Thanks for the code. In tokenize function, I have come across the below snippet 

```
        while start_idx >= len(labels):
            start_idx -= 1
```

If you don't mind, can you please help me understand with an example. Thank you for your time.

**Comment by nbroad1881** [comment]
I didn't want to get an index error. If `start_idx` had been incremented beyond the length of the labels, then I would keep decreasing it until it fit.

**Comment by jamesjohnson1025** [comment]
Thank you.
